name: saasify
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio:
  intl:
  get_it:
  flutter_svg:
  flutter_bloc:
  firebase_auth:
  firebase_core:
  cupertino_icons:
  shared_preferences:
  image_picker:
  percent_indicator:
  calendar_date_picker2:
  table_calendar:
  data_table_2:
  fl_chart:
  pdf:
  file_picker:
  cloud_firestore:
  dropdown_button2: ^2.3.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  hive_generator:
  build_runner:

flutter:

  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: PT_Sans
      fonts:
        - asset: assets/fonts/PT_Sans/PTSans-Bold.ttf
        - asset: assets/fonts/PT_Sans/PTSans-Regular.ttf
