name: saasify
description: This ERP software integrates HR, POS, and Accounting modules to streamline business processes. Manage employee data, automate sales transactions, and handle accounting seamlessly for enhanced organizational efficiency.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.0
  pdf: ^3.10.8
  intl: ^0.19.0
  uuid:
  path: ^1.9.0
  hive: ^2.2.3
  get_it: ^7.6.7
  printing: ^5.12.0
  equatable: ^2.0.5
  dotted_line: ^3.2.2
  flutter_svg: ^2.0.9
  image_picker: ^1.1.0
  flutter_bloc: ^8.1.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  firebase_auth: ^4.19.3
  firebase_core: ^2.30.1
  cupertino_icons: ^1.0.6
  cloud_firestore: ^4.17.1
  firebase_storage: ^11.7.3
  connectivity_plus:
  shared_preferences: ^2.2.2
  firebase_crashlytics: ^3.5.1
  cached_network_image:



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  hive_generator: ^2.0.1
  build_runner: ^2.0.5

flutter:

  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: PT_Sans
      fonts:
        - asset: assets/fonts/PT_Sans/PTSans-Bold.ttf
        - asset: assets/fonts/PT_Sans/PTSans-Regular.ttf
