name: Deploy App to Firebase Hosting

on:
  push:
    branches:
      - dev

jobs:
  build_and_preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Runner
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Flutter Build Web
        run: flutter build web --source-maps --web-renderer=canvaskit

      - name: Deploy to Firebase Hosting
        run: |
          /usr/local/bin/npx firebase-tools@latest hosting:channel:deploy ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.head_ref }} --expires 7d --project ${{ secrets.FIREBASE_PROJECT_ID }} --json
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
