name: Deploy to Testing

on:
  push:
    branches:
      - dev

jobs:
  build_and_preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Clear Flutter cache
        run: flutter clean

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Runner
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Flutter Build Web
        run: flutter build web --web-renderer html --release

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Debug
        run: |
          echo "GitHub Event Name: ${{ github.event_name }}"
          echo "GitHub Ref: ${{ github.ref }}"
          echo "GitHub PR Head Ref: ${{ github.event.pull_request.head.ref }}"

      - name: Deploy to Firebase Hosting
        run: |
          firebase --version  # Print Firebase CLI version for debugging
          npx firebase-tools hosting:channel:deploy $(if [ "${{ github.event_name }}" == 'pull_request' ]; then echo "${{ github.event.pull_request.head.ref }}"; else echo "${{ github.ref }}"; fi) --project ${{ secrets.FIREBASE_PROJECT_ID }} --token ${{ secrets.FIREBASE_TOKEN }} --only hosting:saasify-dev --json
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
