name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - dev

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Setup Flutter environment
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Run Flutter dependencies
        run: flutter pub get

      - name: Build Web app
        run: flutter build web --release --web-renderer canvaskit --no-tree-shake-icons
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SAASIFY_5DDD8 }}'
          channelId: live
          projectId: saasify-5ddd8
          target: "saasify-test"
