name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.2'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install dependencies
        run: flutter pub get

      - name: Build for web
        run: flutter build web

      - name: Login to Firebase (using the branch you want)
        run: firebase login:ci --no-localhost

      - name: Deploy to Firebase Hosting (accessing token from secret)
        run: firebase deploy --only hosting --token "${{ secrets.PROD_FIREBASE_TOKEN }}"
