name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build for web
        run: flutter build web

      - name: Login to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: login:ci

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --token "${{ secrets.PROD_FIREBASE_TOKEN }}"
