name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v3
      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: 📦 Install Dependencies
        run: |
          flutter pub global activate very_good_cli
          very_good --analytics false
          very_good packages get --recursive
      - name: 🛠️ Build the application
        run: flutter build web
      - name: ⬇️ Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/web

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 📚 Checkout repo
        uses: actions/checkout@v3
      - name: ⬇️ Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build/web
      - name: 🎯 Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.PROD_FIREBASE_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}"
          channelId: live
          projectId: saasify-production
