name: Deploy to Production

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.2'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Run Flutter doctor
        run: flutter doctor

      - name: Flutter clean
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Build for web
        run: flutter build web

      - name: Login to Firebase (using service account)
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT_KEY" > firebase-admin-sdk.json
          firebase login:ci --token "$FIREBASE_SERVICE_ACCOUNT_KEY"
      

      - name: Deploy to Firebase Hosting (accessing token from secret)
        run: firebase deploy --only hosting --token "${{ secrets.PROD_FIREBASE_TOKEN }}"
